[package]
name = "ext-time"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.80" }
serde = { version = "1.0.197", features = ["derive"]}
time = { version = "0.3.36", features = [
    "macros",
    "formatting",
    "parsing",
    "local-offset",
]}